"""
Reader for Claude Code hook logs
Parses session logs generated by hooks
"""

import json
import logging
from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class HookSessionSummary:
    """Summary of hook data for a session"""

    session_id: str
    total_tools: int
    tools_by_type: dict[str, int]
    blocked_operations: int
    tools_with_errors: int
    timestamps: list[str]


class HooksReader:
    """Reads and aggregates Claude Code hook logs"""

    def __init__(self, sessions_dir: str = "logs/sessions"):
        self.sessions_dir = Path(sessions_dir)
        logger.info(f"HooksReader initialized for {self.sessions_dir}")

    def get_all_sessions(self) -> list[str]:
        """Get list of all session IDs"""
        if not self.sessions_dir.exists():
            return []

        return [d.name for d in self.sessions_dir.iterdir() if d.is_dir()]

    def read_session_summary(self, session_id: str) -> HookSessionSummary | None:
        """Read summary for a specific session"""
        summary_file = self.sessions_dir / session_id / "summary.json"

        if not summary_file.exists():
            return None

        try:
            with open(summary_file) as f:
                data = json.load(f)

            return HookSessionSummary(
                session_id=data.get("task_id", session_id),
                total_tools=data.get("total_tools_used", 0),
                tools_by_type=data.get("tools_by_type", {}),
                blocked_operations=data.get("blocked_operations", 0),
                tools_with_errors=data.get("tools_with_errors", 0),
                timestamps=[],
            )
        except Exception as e:
            logger.error(f"Error reading session summary {session_id}: {e}")
            return None

    def read_session_pre_tools(self, session_id: str) -> list[dict]:
        """Read pre-tool logs for a session"""
        pre_file = self.sessions_dir / session_id / "pre_tool_use.jsonl"

        if not pre_file.exists():
            return []

        try:
            tools = []
            with open(pre_file) as f:
                for line in f:
                    if line.strip():
                        tools.append(json.loads(line))
            return tools
        except Exception as e:
            logger.error(f"Error reading pre-tool logs {session_id}: {e}")
            return []

    def read_session_post_tools(self, session_id: str) -> list[dict]:
        """Read post-tool logs for a session"""
        post_file = self.sessions_dir / session_id / "post_tool_use.jsonl"

        if not post_file.exists():
            return []

        try:
            tools = []
            with open(post_file) as f:
                for line in f:
                    if line.strip():
                        tools.append(json.loads(line))
            return tools
        except Exception as e:
            logger.error(f"Error reading post-tool logs {session_id}: {e}")
            return []

    def get_aggregate_statistics(self, hours: int = 24) -> dict[str, Any]:
        """Get aggregate statistics from all sessions"""
        cutoff = datetime.now().timestamp() - (hours * 3600)

        total_sessions = 0
        total_tools = 0
        tools_by_type = defaultdict(int)
        total_blocked = 0
        total_errors = 0
        recent_sessions = []

        for session_id in self.get_all_sessions():
            # Check if session is within time window (using directory mtime as proxy)
            session_dir = self.sessions_dir / session_id
            if session_dir.stat().st_mtime < cutoff:
                continue

            # Try to read summary, if not available compute from logs
            summary = self.read_session_summary(session_id)
            if not summary:
                # Compute summary from log files
                post_tools = self.read_session_post_tools(session_id)
                pre_tools = self.read_session_pre_tools(session_id)

                if not post_tools:
                    continue

                # Count tools by type
                session_tools_by_type = defaultdict(int)
                for tool in post_tools:
                    tool_name = tool.get("tool", "unknown")
                    session_tools_by_type[tool_name] += 1

                # Count blocked and errors
                session_blocked = len([t for t in pre_tools if t.get("status") == "blocked"])
                session_errors = len([t for t in post_tools if t.get("has_error", False)])

                summary = HookSessionSummary(
                    session_id=session_id,
                    total_tools=len(post_tools),
                    tools_by_type=dict(session_tools_by_type),
                    blocked_operations=session_blocked,
                    tools_with_errors=session_errors,
                    timestamps=[],
                )

            total_sessions += 1
            total_tools += summary.total_tools
            total_blocked += summary.blocked_operations
            total_errors += summary.tools_with_errors

            for tool, count in summary.tools_by_type.items():
                tools_by_type[tool] += count

            recent_sessions.append(
                {
                    "session_id": session_id,
                    "total_tools": summary.total_tools,
                    "blocked": summary.blocked_operations,
                    "errors": summary.tools_with_errors,
                }
            )

        return {
            "time_window_hours": hours,
            "total_sessions": total_sessions,
            "total_tool_calls": total_tools,
            "total_blocked_operations": total_blocked,
            "total_errors": total_errors,
            "tools_by_type": dict(tools_by_type),
            "recent_sessions": sorted(recent_sessions, key=lambda x: x["total_tools"], reverse=True)[:20],
        }

    def get_session_timeline(self, session_id: str) -> list[dict]:
        """Get complete timeline of events for a session"""
        pre_tools = self.read_session_pre_tools(session_id)
        post_tools = self.read_session_post_tools(session_id)

        # Combine and sort by timestamp
        events = []

        for tool in pre_tools:
            events.append(
                {
                    "timestamp": tool.get("timestamp"),
                    "type": "pre_tool",
                    "tool": tool.get("tool"),
                    "status": tool.get("status"),
                    "parameters": tool.get("parameters", {}),
                }
            )

        for tool in post_tools:
            events.append(
                {
                    "timestamp": tool.get("timestamp"),
                    "type": "post_tool",
                    "tool": tool.get("tool"),
                    "output_length": tool.get("output_length"),
                    "has_error": tool.get("has_error", False),
                }
            )

        # Sort by timestamp (handle None timestamps)
        events.sort(key=lambda e: e.get("timestamp") or "")

        return events
